"""Базовый класс моделей и общие кирпичики схемы.

Правила схемы (раздел 5 ТЗ) собраны здесь, чтобы не повторять их в каждой таблице:
ключи BIGINT IDENTITY, суммы в копейках с CHECK (>= 0), время — timestamptz.
"""

from __future__ import annotations

import datetime as dt
from enum import StrEnum
from typing import Any

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    DateTime,
    Enum,
    Identity,
    MetaData,
    func,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Единые имена ограничений: без них Alembic в autogenerate придумывает свои
# и потом не может их удалить.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class IdMixin:
    """Первичный ключ: BIGINT GENERATED BY DEFAULT AS IDENTITY."""

    id: Mapped[int] = mapped_column(
        BigInteger,
        Identity(always=False, start=1),
        primary_key=True,
    )


class TimestampMixin:
    """Когда запись создана и когда её меняли в последний раз."""

    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class SortableMixin:
    """Справочники, порядок в которых задаёт владелица."""

    sort_order: Mapped[int] = mapped_column(BigInteger, default=0, server_default="0")
    is_active: Mapped[bool] = mapped_column(default=True, server_default="true")


def enum_type(enum_cls: type[StrEnum], name: str, *, length: int = 32) -> Enum:
    """Код из StrEnum -> VARCHAR + CHECK по списку значений.

    Нативный тип Postgres не используем: добавить значение в CHECK проще,
    чем в ENUM, а на чтении SQLAlchemy всё равно отдаёт member класса.
    """
    return Enum(
        enum_cls,
        name=name,
        native_enum=False,
        length=length,
        create_constraint=True,
        validate_strings=True,
        values_callable=lambda cls: [member.value for member in cls],
    )


def money(**kwargs: Any) -> Any:
    """Сумма в копейках. CHECK (>= 0) вешается на таблицу отдельно, через non_negative()."""
    kwargs.setdefault("nullable", False)
    return mapped_column(BigInteger, **kwargs)


def non_negative(column: str) -> CheckConstraint:
    return CheckConstraint(f"{column} >= 0", name=f"{column}_non_negative")


def positive(column: str) -> CheckConstraint:
    return CheckConstraint(f"{column} > 0", name=f"{column}_positive")
